### ISSUE TITLE
vncserver.dll

### ISSUE THREAD

**Issue by HelloJango** [andremussche/UltraVncAsDll#6]
hi,which project to generate the vncserver.dll,i can not find the vncserver.dll,but your release dir has this file

**Comment by andremussche** [comment]
I think this is the solution you need to load in VisualStudio:
https://github.com/andremussche/UltraVncAsDll/blob/master/winvnc/winvnc.sln

This will contain this project:
https://github.com/andremussche/UltraVncAsDll/blob/master/winvnc/winvncdll/winvncdll.vcxproj
